### PR TITLE
 Remove unused $status property 

### PR DESCRIPTION
**Pull request by kelunik**

### CODE REVIEW

**Comment by clue** [comment]
@kelunik Good catch, thanks for looking into this! It looks like this is indeed a small left-over from my changes in #55. May I ask you to squash your changes into a single commit?

**Comment by kelunik** [comment]
@clue Can just use squash on merge, no?

**Comment by SimonFrings** [comment]
@kelunik We try to avoid squashing changes via GitHub's squash on merge. This will always lead to GitHub being the new committer and it will also add an extra commit.

**Comment by SimonFrings** [comment]
@kelunik Checking if this ticket will receive any updates or can we close this? Been open for a while and we want to avoid having issues or pull requests laying around for too long.

It would involve squashing the two commits into one and then force pushing the new commit to GitHub in order for us to approve this. Or is there any way we can help this progressing?

**Comment by SimonFrings** [comment]
This ticket hasn't received any updated in a while, so I'll close this for now. We can always revisit this at a later time.

**Pull request closed without merging**
